# Yasser FAHMI

# Collection des commentaires produits d’amazone

In [92]:
import requests
from bs4 import BeautifulSoup
import time
import random
import pandas as pd
import re
from unidecode import unidecode
import pickle
note=[]
texte=[]
head={
"Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
"User-Agent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"}
for i in range(1,800):
    url='https://www.amazon.fr/quatre-accords-tolt%C3%A8ques-libert%C3%A9-personnelle/product-reviews/2889116549/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber={}'.format(str(i))
    r=requests.get(url,headers=head)
    print(url,r.status_code)
    soup=BeautifulSoup(r.content)
    
    for elem in soup.findAll('i',attrs={"data-hook":"review-star-rating"}):
        note.append(elem.text.split(',')[0])

    for elem in soup.findAll('span',attrs={"data-hook":"review-body"}):
        texte.append(elem.text.strip())

    print("iteration : ",i,"/ longueur liste ",len(note),len(texte))
    
    if (len(note),len(texte)) != (i*10,i*10):
        m=min(len(note),len(texte))
        note=note[:m]
        texte=texte[:m]
        break



https://www.amazon.fr/quatre-accords-tolt%C3%A8ques-libert%C3%A9-personnelle/product-reviews/2889116549/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=1 200
iteration :  1 / longueur liste  10 10
https://www.amazon.fr/quatre-accords-tolt%C3%A8ques-libert%C3%A9-personnelle/product-reviews/2889116549/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=2 200
iteration :  2 / longueur liste  20 20
https://www.amazon.fr/quatre-accords-tolt%C3%A8ques-libert%C3%A9-personnelle/product-reviews/2889116549/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=3 200
iteration :  3 / longueur liste  30 30
https://www.amazon.fr/quatre-accords-tolt%C3%A8ques-libert%C3%A9-personnelle/product-reviews/2889116549/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=4 200
iteration :  4 / longueur liste  40 40
https://www.amazon.fr/quatre-accords-tolt%C3%A8ques-libert%C3%A9-personnelle/product-reviews

https://www.amazon.fr/quatre-accords-tolt%C3%A8ques-libert%C3%A9-personnelle/product-reviews/2889116549/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=37 200
iteration :  37 / longueur liste  370 370
https://www.amazon.fr/quatre-accords-tolt%C3%A8ques-libert%C3%A9-personnelle/product-reviews/2889116549/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=38 200
iteration :  38 / longueur liste  380 380
https://www.amazon.fr/quatre-accords-tolt%C3%A8ques-libert%C3%A9-personnelle/product-reviews/2889116549/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=39 200
iteration :  39 / longueur liste  390 390
https://www.amazon.fr/quatre-accords-tolt%C3%A8ques-libert%C3%A9-personnelle/product-reviews/2889116549/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=40 200
iteration :  40 / longueur liste  400 400
https://www.amazon.fr/quatre-accords-tolt%C3%A8ques-libert%C3%A9-personnelle

https://www.amazon.fr/quatre-accords-tolt%C3%A8ques-libert%C3%A9-personnelle/product-reviews/2889116549/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=73 200
iteration :  73 / longueur liste  730 730
https://www.amazon.fr/quatre-accords-tolt%C3%A8ques-libert%C3%A9-personnelle/product-reviews/2889116549/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=74 200
iteration :  74 / longueur liste  740 740
https://www.amazon.fr/quatre-accords-tolt%C3%A8ques-libert%C3%A9-personnelle/product-reviews/2889116549/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=75 200
iteration :  75 / longueur liste  750 750
https://www.amazon.fr/quatre-accords-tolt%C3%A8ques-libert%C3%A9-personnelle/product-reviews/2889116549/ref=cm_cr_arp_d_paging_btm_next_2?ie=UTF8&reviewerType=all_reviews&pageNumber=76 200
iteration :  76 / longueur liste  760 760
https://www.amazon.fr/quatre-accords-tolt%C3%A8ques-libert%C3%A9-personnelle

In [93]:
pip install unidecode

Note: you may need to restart the kernel to use updated packages.


In [121]:
t=pd.DataFrame({'Texte':texte,'Note':note})

In [122]:
t.to_csv('Tolteques.csv',index=False)

In [123]:
df=pd.read_csv('Tolteques.csv')

In [173]:
df

Texte  Note
0     J’avoue que le titre est intrigant, accrocheur...     0
1     Quand on pense que c'est un succès mondial, on...     0
3     Devant les commentaires dithyrambique de cet o...     0
5     Vraiment Impatiente de découvrir ce livre ence...     0
6     Je me joindrai à beaucoup et je vais probablem...     1
...                                                 ...   ...
1055  Livre et enseignement passionnément captivant ...     1
1056                                          tres bien     1
1057                           Expérience enrichissante     1
1058  un livre qui doit être dans toutes les bibliot...     1
1059  L’une de mes meilleurs lectures. Il y a un ava...     1

[1006 rows x 2 columns]

# Nettoyage

In [98]:
df=pd.read_csv('Tolteques.csv')

In [99]:
print(df.shape)
df.drop_duplicates(subset=['Texte'],inplace=True)
df.shape

(1060, 2)


(1028, 2)

In [100]:
seuil_mot=10
def nb_mot(texte):
    return len(texte.split(' '))

df['Longueur']=df['Texte'].apply(nb_mot)
df=df[df['Longueur']>seuil_mot]

In [125]:
df['Note'].value_counts()

# Binarisation 0 (1,2,3) / 1 (4,5)
df.loc[df[df['Note'].astype(int)<3].index,'Note']=0
df.loc[df[df['Note'].astype(int)>3].index,'Note']=1
df=df[df['Note']!=3]
# Je prends autant de texte positif que negatif (don j'identifie le label le moins present)
m=df['Note'].value_counts().min()
Comments=pd.concat([df[df['Note'].astype(int)==1].sample(m),df[df['Note'].astype(int)==0].sample(m)])

In [126]:
Comments['Note'].value_counts()

1    98
0    98
Name: Note, dtype: int64

In [103]:
def nettoyage(texte):
    lem=pickle.load(open('lemmatize_fr.pickle','rb'))
    #Je charge la liste de stop words
    with open('stop-w_fr.txt') as f:
        s_w=f.read().split('\n')

    tmp=[]
    # Normalisation : accents et minuscule
    texte=unidecode(texte.lower())
    p='[a-z]{2,}'
    for mot in re.findall(p,texte):
        if mot in s_w:
            continue
        else:
            tmp.append(mot)
    return ' '.join(tmp)

nettoyage("élément à modifier chez Mr Bean")

'element modifier mr bean'

In [104]:
negatif=[nettoyage(elem) for elem in Comments[Comments['Note']==0]['Texte']]
positif=[nettoyage(elem) for elem in Comments[Comments['Note']==1]['Texte']]

# featurisation

# TF-IDF

In [105]:
from sklearn.feature_extraction.text import TfidfVectorizer
#On prend les mots par groupe de 2,3 et 4
vectorizer = TfidfVectorizer(ngram_range=(2, 4))
#On utilise le vectorizer sur les commentaires positifs
X = vectorizer.fit_transform(positif)
print(vectorizer.get_feature_names())

print(X.shape)

['abordable facile', 'abordable facile lire', 'abordable facile lire depart', 'acceptent remettre', 'acceptent remettre question', 'acceptent remettre question cherchent', 'acceptes faut', 'acceptes faut temps', 'acceptes faut temps apprentissage', 'accessible achete', 'accessible achete regulierement', 'accessible achete regulierement livres', 'accessible necessite', 'accessible necessite connaissances', 'accessible necessite connaissances particulieres', 'accessible vrai', 'accessible vrai bcp', 'accessible vrai bcp aime', 'accord recommande', 'accord recommande enthousiasme', 'accord voyage', 'accord voyage vivre', 'accord voyage vivre don', 'accords code', 'accords code conduite', 'accords code conduite acceptes', 'accords conseille', 'accords conseille vivement', 'accords conseille vivement travail', 'accords decouvre', 'accords decouvre lecons', 'accords decouvre lecons vie', 'accords essentiels', 'accords essentiels vraiment', 'accords essentiels vraiment vie', 'accords fondamen

In [106]:
Mat=pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names())
Mat

abordable facile  abordable facile lire  abordable facile lire depart  \
0                0.0                    0.0                           0.0   
1                0.0                    0.0                           0.0   
2                0.0                    0.0                           0.0   
3                0.0                    0.0                           0.0   
4                0.0                    0.0                           0.0   
..               ...                    ...                           ...   
81               0.0                    0.0                           0.0   
82               0.0                    0.0                           0.0   
83               0.0                    0.0                           0.0   
84               0.0                    0.0                           0.0   
85               0.0                    0.0                           0.0   

    acceptent remettre  acceptent remettre question  \
0                  0.0                          0.0   
1                  0.0                          0.0   
2                  0.0                          0.0   
3                  0.0                          0.0   
4                  0.0                          0.0   
..                 ...                          ...   
81                 0.0                          0.0   
82                 0.0                          0.0   
83                 0.0                          0.0   
84                 0.0                          0.0   
85                 0.0                          0.0   

    acceptent remettre question cherchent  acceptes faut  acceptes faut temps  \
0                                     0.0            0.0                  0.0   
1                                     0.0            0.0                  0.0   
2                                     0.0            0.0                  0.0   
3                                     0.0            0.0                  0.0   
4                                     0.0            0.0                  0.0   
..                                    ...            ...                  ...   
81                                    0.0            0.0                  0.0   
82                                    0.0            0.0                  0.0   
83                                    0.0            0.0                  0.0   
84                                    0.0            0.0                  0.0   
85                                    0.0            0.0                  0.0   

    acceptes faut temps apprentissage  accessible achete  ...  \
0                                 0.0                0.0  ...   
1                                 0.0                0.0  ...   
2                                 0.0                0.0  ...   
3                                 0.0                0.0  ...   
4                                 0.0                0.0  ...   
..                                ...                ...  ...   
81                                0.0                0.0  ...   
82                                0.0                0.0  ...   
83                                0.0                0.0  ...   
84                                0.0                0.0  ...   
85                                0.0                0.0  ...   

    vraiment produit efficace aider  vraiment remettre  \
0                               0.0                0.0   
1                               0.0                0.0   
2                               0.0                0.0   
3                               0.0                0.0   
4                               0.0                0.0   
..                              ...                ...   
81                              0.0                0.0   
82                              0.0                0.0   
83                              0.0                0.0   
84                              0.0                0.0   
85                        

In [249]:
from sklearn.feature_extraction.text import TfidfVectorizer
#On prend les mots par groupe de 2,3 et 4
vectorizer = TfidfVectorizer(ngram_range=(2, 4))
#On utilise le vectorizer sur les commentaires négatifs
X = vectorizer.fit_transform(negatif)
print(vectorizer.get_feature_names())

print(X.shape)

['abaissant capacite', 'abaissant capacite individus', 'abaissant capacite individus confronter', 'abandonne idee', 'abandonne idee trouver', 'abandonne idee trouver achat', 'aborde lecture', 'aborde lecture livre', 'aborde lecture livre rapidement', 'absolu enfant', 'absolu enfant prophetie', 'absolu enfant prophetie accords', 'absolu exemple', 'absolu exemple histoireem', 'absolu exemple histoireem faire', 'abstraits mal', 'abstraits mal rattacher', 'abstraits mal rattacher vie', 'abuser quatrieme', 'abuser quatrieme couverture', 'abuser quatrieme couverture cite', 'acabit dirait', 'acabit dirait recueil', 'acabit dirait recueil articles', 'acceder bonheur', 'acceder bonheur absolu', 'acceder bonheur absolu enfant', 'accepte monde', 'accepte monde realites', 'accepte monde realites vie', 'acceptent oui', 'acceptent oui savons', 'acceptent oui savons lire', 'accepter refuser', 'accepter refuser precepte', 'accepter refuser precepte recu', 'accessibles pratiques', 'accompagne maitre', 

In [250]:
Mat=pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names())
Mat

abaissant capacite  abaissant capacite individus  \
0                  0.0                           0.0   
1                  0.0                           0.0   
2                  0.0                           0.0   
3                  0.0                           0.0   
4                  0.0                           0.0   
..                 ...                           ...   
81                 0.0                           0.0   
82                 0.0                           0.0   
83                 0.0                           0.0   
84                 0.0                           0.0   
85                 0.0                           0.0   

    abaissant capacite individus confronter  abandonne idee  \
0                                       0.0             0.0   
1                                       0.0             0.0   
2                                       0.0             0.0   
3                                       0.0             0.0   
4                                       0.0             0.0   
..                                      ...             ...   
81                                      0.0             0.0   
82                                      0.0             0.0   
83                                      0.0             0.0   
84                                      0.0             0.0   
85                                      0.0             0.0   

    abandonne idee trouver  abandonne idee trouver achat  aborde lecture  \
0                      0.0                           0.0             0.0   
1                      0.0                           0.0             0.0   
2                      0.0                           0.0             0.0   
3                      0.0                           0.0             0.0   
4                      0.0                           0.0             0.0   
..                     ...                           ...             ...   
81                     0.0                           0.0             0.0   
82                     0.0                           0.0             0.0   
83                     0.0                           0.0             0.0   
84                     0.0                           0.0             0.0   
85                     0.0                           0.0             0.0   

    aborde lecture livre  aborde lecture livre rapidement  absolu enfant  ...  \
0                    0.0                              0.0        0.00000  ...   
1                    0.0                              0.0        0.00000  ...   
2                    0.0                              0.0        0.00000  ...   
3                    0.0                              0.0        0.00000  ...   
4                    0.0                              0.0        0.00000  ...   
..                   ...                              ...            ...  ...   
81                   0.0                              0.0        0.06099  ...   
82                   0.0                              0.0        0.00000  ...   
83                   0.0                              0.0        0.00000  ...   
84                   0.0                              0.0        0.00000  ...   
85                   0.0                              0.0        0.00000  ...   

    vue personnel aime cote  wikipedia auteur  wikipedia auteur blabla  \
0                       0.0           0.00000                  0.00000   
1                       0.0           0.07191                  0.07191   
2                       0.0           0.00000                  0.00000   
3                       0.0           0.00000                  0.00000   
4                       0.0           0.00000                  0.00000   
..                      ...               ...                      ...   
81                      0.0           0.00000                  0.00000   
82                      0.0           0.00000                  0.00000   
83                    

# word2vec

In [107]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
#On utilise le vectorizer sur les commentaires negatifs
X = vectorizer.fit_transform(negatif)
print(vectorizer.get_feature_names())

print(X.toarray())

['abaissant', 'abandonne', 'abimees', 'aborde', 'abruti', 'absolu', 'abstraits', 'abuser', 'acabit', 'acceder', 'accepte', 'acceptent', 'accepter', 'accessibles', 'accompagne', 'accompli', 'accord', 'accords', 'accroche', 'accrocher', 'accrocheur', 'achat', 'achate', 'achetant', 'achete', 'acheter', 'acheve', 'actuelle', 'adepte', 'adeptes', 'affaire', 'affirmations', 'affirme', 'affirmer', 'affligeante', 'agacant', 'age', 'ages', 'agit', 'aide', 'aider', 'aimantee', 'aime', 'aimerai', 'air', 'aise', 'alambique', 'alchimiste', 'allais', 'allait', 'allee', 'aller', 'allez', 'alternatives', 'amalgame', 'amazon', 'ameliorer', 'amene', 'americains', 'ami', 'amour', 'an', 'analyser', 'ancestral', 'ancienne', 'anciennes', 'anges', 'animal', 'annees', 'annule', 'ans', 'antigel', 'antinomique', 'antisocial', 'apathie', 'apparaissent', 'appele', 'appelles', 'application', 'appliquant', 'applique', 'appliquer', 'apporte', 'apprecie', 'apprend', 'apprendre', 'apprenons', 'apprentissage', 'approfo


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]


In [108]:
Neg=pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names())
Neg

abaissant  abandonne  abimees  aborde  abruti  absolu  abstraits  abuser  \
0           0          0        0       0       0       0          0       0   
1           0          0        0       0       0       0          0       0   
2           0          0        0       0       0       0          0       0   
3           0          0        0       0       0       0          0       0   
4           0          0        0       0       0       0          0       0   
..        ...        ...      ...     ...     ...     ...        ...     ...   
81          0          0        0       0       0       1          0       0   
82          0          0        1       0       0       0          0       0   
83          0          0        0       0       0       0          0       0   
84          0          0        0       0       0       0          0       0   
85          0          0        0       0       0       0          0       0   

    acabit  acceder  ...  vouloir  voyage  vrai  vraie  vraies  vraiment  vue  \
0        0        0  ...        0       0     0      0       0         0    0   
1        0        0  ...        0       0     0      0       0         2    0   
2        0        0  ...        0       0     0      0       0         0    0   
3        0        0  ...        0       0     0      0       0         0    0   
4        0        0  ...        0       0     0      0       0         0    0   
..     ...      ...  ...      ...     ...   ...    ...     ...       ...  ...   
81       0        1  ...        1       0     0      0       0         0    0   
82       0        0  ...        0       0     0      0       0         0    0   
83       0        0  ...        0       0     0      0       0         0    0   
84       0        0  ...        0       0     0      0       0         0    0   
85       0        0  ...        0       0     0      0       0         0    0   

    wikipedia  winfray  zen  
0           0        0    0  
1           1        0    0  
2           0        0    0  
3           0        0    0  
4           0        0    0  
..        ...      ...  ...  
81          0        0    1  
82          0        0    0  
83          0        0    0  
84          0        1    0  
85          0        0    0  

[86 rows x 1350 columns]

In [251]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
#On utilise le vectorizer sur les commentaires positifs
X = vectorizer.fit_transform(positif)
print(vectorizer.get_feature_names())

print(X.toarray())

['abordable', 'acceder', 'acceptent', 'acceptes', 'accessible', 'accord', 'accords', 'achat', 'achete', 'acheter', 'actuelle', 'adapter', 'adherer', 'adore', 'adoucit', 'age', 'agit', 'agnes', 'aide', 'aidee', 'aider', 'aiderait', 'aime', 'aimer', 'air', 'aisance', 'ajoute', 'ajouterai', 'allant', 'aller', 'amateur', 'amie', 'amis', 'amour', 'analyse', 'anglo', 'annees', 'annonceur', 'ans', 'anxiete', 'apaisante', 'apaise', 'apaisevous', 'apercois', 'application', 'applications', 'appliquant', 'appliquer', 'apporte', 'apprecie', 'apprehender', 'apprehension', 'apprend', 'apprendre', 'apprentissage', 'approche', 'arrive', 'arriver', 'article', 'aspire', 'assimiler', 'attentes', 'attention', 'aucours', 'autour', 'avance', 'avancer', 'avenir', 'avis', 'bases', 'bcp', 'belle', 'besoin', 'bible', 'bibliotheque', 'bienveillance', 'blessee', 'bluffant', 'bonheur', 'bonheurde', 'bonne', 'bonnes', 'bons', 'bosser', 'bouleversement', 'ca', 'calendriers', 'captivant', 'carton', 'cas', 'castaneda'

In [252]:
pos=pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names())
pos

abordable  acceder  acceptent  acceptes  accessible  accord  accords  \
0           0        0          0         0           0       1        1   
1           0        0          0         0           0       0        1   
2           0        0          0         0           0       0        0   
3           0        0          0         0           0       0        0   
4           0        0          0         0           0       0        0   
..        ...      ...        ...       ...         ...     ...      ...   
81          0        0          0         0           0       0        0   
82          0        0          0         0           0       0        0   
83          0        0          0         0           0       0        0   
84          0        0          0         0           0       0        0   
85          0        0          0         0           0       0        0   

    achat  achete  acheter  ...  voila  voir  vois  volets  voulez  voyage  \
0       0       0        0  ...      0     0     0       0       0       0   
1       0       0        0  ...      0     0     0       0       0       0   
2       0       0        0  ...      0     0     0       0       0       0   
3       0       0        0  ...      0     0     0       0       0       0   
4       0       0        0  ...      1     0     0       0       0       0   
..    ...     ...      ...  ...    ...   ...   ...     ...     ...     ...   
81      0       0        0  ...      0     0     0       0       0       0   
82      0       0        0  ...      1     0     0       0       0       0   
83      0       0        0  ...      0     0     0       0       0       0   
84      0       0        0  ...      0     0     0       0       0       0   
85      0       0        0  ...      0     0     0       0       0       0   

    voyais  vrai  vraiment  yeux  
0        0     0         1     0  
1        0     0         0     0  
2        0     0         0     1  
3        0     0         0     0  
4        0     0         0     0  
..     ...   ...       ...   ...  
81       0     0         0     0  
82       0     0         0     0  
83       0     0         1     0  
84       0     0         0     0  
85       0     1         0     0  

[86 rows x 652 columns]

# Camembert

In [109]:
import torch
from transformers import CamembertTokenizer,CamembertModel

tokenizer = CamembertTokenizer.from_pretrained('camembert/camembert-large')
model = CamembertModel.from_pretrained('camembert/camembert-large',output_hidden_states=True)

In [110]:
#appliquer le Camembert sur les commentaires positifs
input_ids = tokenizer.encode(positif,return_tensors='pt') 

# 2)
outputs = model(input_ids)
outputs[2][-4:]

(tensor([[[ 0.1685,  0.2772,  0.1522,  ...,  0.1645,  0.0516, -0.2938],
          [ 0.3971,  0.1200,  0.2661,  ...,  0.4234, -0.1394, -0.1272],
          [-0.0338, -0.5482,  0.0791,  ...,  0.5142,  0.1099,  0.0821],
          ...,
          [-0.3374, -0.6388,  0.4076,  ...,  0.3974,  0.2144, -0.0496],
          [-0.5665, -0.5869,  0.3450,  ...,  0.4677,  0.2049,  0.2122],
          [-0.0146, -0.0321,  0.0413,  ...,  0.0061, -0.0150, -0.0319]]],
        grad_fn=<NativeLayerNormBackward>),
 tensor([[[ 0.0360,  0.3119,  0.3603,  ...,  0.4207,  0.1060, -0.0215],
          [ 0.1662,  0.1089,  0.0908,  ...,  0.3848, -0.1580, -0.0037],
          [-0.0355, -0.5581,  0.0106,  ...,  0.2107,  0.1797, -0.1724],
          ...,
          [ 0.0976, -0.2240,  0.1379,  ..., -0.0939, -0.0399, -0.1776],
          [-0.0181, -0.2880,  0.1981,  ...,  0.1502, -0.0040,  0.0071],
          [-0.0251, -0.0269,  0.0242,  ...,  0.0265,  0.0261, -0.0508]]],
        grad_fn=<NativeLayerNormBackward>),
 tensor([[[ 0.

In [111]:
import pandas as pd
import numpy as np

l=[]
for i in range(-1,-5,-1):
    l.append(pd.DataFrame(np.mean(outputs[2][i].squeeze(0).detach().numpy(),axis=0)).T)
    
pd.concat(l,ignore_index=True).mean(axis=0)

0      -0.238684
1      -0.402253
2      -0.071001
3      -0.355788
4       0.010870
          ...   
1019   -0.277988
1020    0.058713
1021    0.172358
1022    0.234612
1023   -0.061331
Length: 1024, dtype: float32

In [255]:
#appliquer le Camembert sur les commentaires negatifs
input_idss = tokenizer.encode(negatif,return_tensors='pt') 

# 2)
outputss = model(input_ids)
outputss[2][-4:]

(tensor([[[ 0.1685,  0.2772,  0.1522,  ...,  0.1645,  0.0516, -0.2938],
          [ 0.3971,  0.1200,  0.2661,  ...,  0.4234, -0.1394, -0.1272],
          [-0.0338, -0.5482,  0.0791,  ...,  0.5142,  0.1099,  0.0821],
          ...,
          [-0.3374, -0.6388,  0.4076,  ...,  0.3974,  0.2144, -0.0496],
          [-0.5665, -0.5869,  0.3450,  ...,  0.4677,  0.2049,  0.2122],
          [-0.0146, -0.0321,  0.0413,  ...,  0.0061, -0.0150, -0.0319]]],
        grad_fn=<NativeLayerNormBackward>),
 tensor([[[ 0.0360,  0.3119,  0.3603,  ...,  0.4207,  0.1060, -0.0215],
          [ 0.1662,  0.1089,  0.0908,  ...,  0.3848, -0.1580, -0.0037],
          [-0.0355, -0.5581,  0.0106,  ...,  0.2107,  0.1797, -0.1724],
          ...,
          [ 0.0976, -0.2240,  0.1379,  ..., -0.0939, -0.0399, -0.1776],
          [-0.0181, -0.2880,  0.1981,  ...,  0.1502, -0.0040,  0.0071],
          [-0.0251, -0.0269,  0.0242,  ...,  0.0265,  0.0261, -0.0508]]],
        grad_fn=<NativeLayerNormBackward>),
 tensor([[[ 0.

In [254]:
import pandas as pd
import numpy as np

l=[]
for i in range(-1,-5,-1):
    l.append(pd.DataFrame(np.mean(outputs[2][i].squeeze(0).detach().numpy(),axis=0)).T)
    
pd.concat(l,ignore_index=True).mean(axis=0)

0      -0.238684
1      -0.402253
2      -0.071001
3      -0.355788
4       0.010870
          ...   
1019   -0.277988
1020    0.058713
1021    0.172358
1022    0.234612
1023   -0.061331
Length: 1024, dtype: float32

# entrainer un classifieur binaire

# Avec tf-idf

In [258]:
from sklearn.feature_extraction.text import TfidfVectorizer
#On prend les mots par groupe de 2,3 et 4
vectorizer = TfidfVectorizer(ngram_range=(2, 4))
#On utilise le vectorizer sur les commentaires 
X1= vectorizer.fit_transform(df['Texte'])
tmp=pd.DataFrame(X1.toarray(),columns=vectorizer.get_feature_names())

In [259]:
X=pd.DataFrame(tmp)
X=X[1:1000]
y=df['Note']
y=y[1:1000]

In [235]:
y

1       0
3       0
5       0
6       1
7       1
       ..
1049    1
1050    1
1051    1
1052    1
1053    1
Name: Note, Length: 999, dtype: int64

In [260]:
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
import sklearn

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

clf = svm.LinearSVC()
clf.fit(X_train, y_train)
y_pred=clf.predict(X_test)


from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X_train, y_train, cv=5)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))


print("Train score : ",clf.score(X_train, y_train))
print("Test score : ",clf.score(X_test, y_test))
y_pred=clf.predict(X_test)
confusion_matrix(y_test, y_pred)
print("precision : ",sklearn.metrics.precision_score(y_test, y_pred))
print("F1 score : ",sklearn.metrics.f1_score(y_test, y_pred))

0.90 accuracy with a standard deviation of 0.00
Train score :  0.9985693848354793
Test score :  0.9133333333333333
precision :  0.9133333333333333
F1 score :  0.9547038327526133


# word2vec

In [270]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
#On utilise le vectorizer sur les commentaires 
X = vectorizer.fit_transform(df['Texte'])
tmpp=pd.DataFrame(X.toarray(),columns=vectorizer.get_feature_names())

In [271]:
X=pd.DataFrame(tmpp)
X=X[1:1000]
y=df['Note']
y=y[1:1000]

In [272]:
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

clf = svm.LinearSVC()
clf.fit(X_train, y_train)
y_pred=clf.predict(X_test)


from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X_train, y_train, cv=5)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))


print("Train score : ",clf.score(X_train, y_train))
print("Test score : ",clf.score(X_test, y_test))
y_pred=clf.predict(X_test)
confusion_matrix(y_test, y_pred)
print("precision : ",sklearn.metrics.precision_score(y_test, y_pred))
print("F1 score : ",sklearn.metrics.f1_score(y_test, y_pred))

0.91 accuracy with a standard deviation of 0.01
Train score :  1.0
Test score :  0.9166666666666666
precision :  0.9307958477508651
F1 score :  0.955595026642984


# Camembert

In [264]:
df=pd.read_csv('Tolteques.csv')

In [265]:
for i in range(0,1059):
    
    input_ids = tokenizer.encode(df['Texte'][i],return_tensors='pt') 


outputs = model(input_ids)

Token indices sequence length is longer than the specified maximum sequence length for this model (804 > 512). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (549 > 512). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (567 > 512). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (565 > 512). Running this sequence through the model will result in indexing errors


In [266]:
l=[]
for i in range(-1,-5,-1):
    l.append(pd.DataFrame(np.mean(outputs[2][i].squeeze(0).detach().numpy(),axis=0)).T)
    
tmp=pd.concat(l,ignore_index=True).mean(axis=0)

In [267]:
df.loc[df[df['Note'].astype(int)<3].index,'Note']=0
df.loc[df[df['Note'].astype(int)>3].index,'Note']=1
df=df[df['Note']!=3]

In [268]:
X=pd.DataFrame(tmp)
X=X[1:1000]
y=df['Note']
y=y[1:1000]

In [269]:
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

clf = svm.LinearSVC()
clf.fit(X_train, y_train)  
y_pred=clf.predict(X_test)


from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, X_train, y_train, cv=5)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))


print("Train score : ",clf.score(X_train, y_train))
print("Test score : ",clf.score(X_test, y_test))
y_pred=clf.predict(X_test)
confusion_matrix(y_test, y_pred)
print("precision : ",sklearn.metrics.precision_score(y_test, y_pred))
print("F1 score : ",sklearn.metrics.f1_score(y_test, y_pred))


0.90 accuracy with a standard deviation of 0.00
Train score :  0.8984263233190272
Test score :  0.9133333333333333
precision :  0.9133333333333333
F1 score :  0.9547038327526133
